#!/usr/bin/env bash
# Displays "Best School" 10 times using while

count=$1
while [[ $count -lt 10 ]]
do
    echo "Best School"
    count=$(( count + 1 ))
    if [[ $count -eq 9 ]]
    then 
        echo "Hi"
    fi
done
